version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django/onrec
    ports:
      - 8000:8000
    image: application:django
    container_name: onrec_backend
    command: gunicorn onRec.wsgi:application --bind 0.0.0.0:8000

